### ISSUE TITLE
Ошибка версий библиотеки и PHP

### ISSUE THREAD

**Issue by Drunvalo-E** [Alekers/tinkoff-open-api#1]
Добрый день.
При установке получаю сообщение:
D:\Program\wamp\www\fi>composer require tsvetkov/tinkoff_open_api

  [InvalidArgumentException]
  Package tsvetkov/tinkoff_open_api has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...
Использую php7.3.21. FА какую версию для совместимости нужно использовать?

**Comment by Alekers** [comment]
Версии php, совместимые с пакетом - ^7.4 || ^8.0
(Лучше поздно, чем никогда)
